services:
  db:
    image: postgres:16-alpine
    container_name: pathific_db
    environment:
      POSTGRES_DB: pathific
      POSTGRES_USER: pathific
      POSTGRES_PASSWORD: pathific_pass
    ports:
      - "5433:5432" #Host container 5433 not 32 (for local)
    volumes:
      - pathific_db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pathific"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../backend/app
      dockerfile: Dockerfile
    container_name: pathific_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pathific
      SPRING_DATASOURCE_USERNAME: pathific
      SPRING_DATASOURCE_PASSWORD: pathific_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pathific_db_data:
